### PR TITLE
fix: keep focus on the initial value

### LINKED ISSUE #90: Creating a combobox - `value` prop resets
Hi there,

I am trying to create a Combobox in combination with the Radix UI popover component, where I want to have a specific item/value pre-selected. I could use the `value` prop on the `Command` component but unfortunately, as soon as I open the Combobox, the value resets to the first item again.

Is there any other way to have an item pre-selected, as the expected behaviour for a Combobox component. It seems quite difficult to create a Combobox using cmdk.

For example, I am using the example from the [docs](https://github.com/pacocoursey/cmdk#command-cmdk-root). Apple is the pre-selected value but this gets reset to Orange as soon as I close and re-open the menu.

### PR DESCRIPTION
**Pull request by joaom00**
Fixes that cmdk always focus on the first item even if another item value is provided.

Closes #90

### CODE REVIEW

File: cmdk/src/index.tsx [hunk 1]
```diff
@@ -592,10 +593,10 @@ const Item = React.forwardRef<HTMLDivElement, ItemProps>((props, forwardedRef) =
...
       ? true
       : context.filter() === false
-      ? true
-      : !state.search
-      ? true
-      : state.filtered.items.get(id) > 0,
+        ? true
+        : !state.search
+          ? true
+          : state.filtered.items.get(id) > 0,
```
Comment (pacocoursey) [inline cmdk/src/index.tsx:599]: Couple of prettier issues here, if you wouldn't mind fixing :)

**Review by pacocoursey — APPROVED** [review]

File: cmdk/src/index.tsx (hunk 1 above)
Comment (joaom00) [reply cmdk/src/index.tsx]: Done!
