### PR TITLE
fix: call `onValueChange` after filtering the list

### LINKED ISSUE #68: Value from `onValueChange` not detecting filtered value
Discovered this when narrowing the input to select only one value, and noticed that the right area didn't change:

https://user-images.githubusercontent.com/1093738/205722637-4a2802d2-c239-4de9-b66f-cbe37d509536.mp4

### PR DESCRIPTION
**Pull request by Andarist**
fixes #68

### CODE REVIEW

File: cmdk/src/index.tsx [hunk 1]
```diff
@@ -178,11 +178,7 @@ const Command = React.forwardRef<HTMLDivElement, CommandProps>((props, forwarded
           // Filter synchronously before emitting back to children
           filterItems()
           sort()
-          schedule(1, () => {
-            // Select the first item and emit again
-            selectFirstItem()
-            store.emit()
```
Comment (Andarist) [inline cmdk/src/index.tsx:184]: we don't need to emit again now because `selectFirstItem` calls into `setState` with the new value and that causes a new emit already

**Review by pacocoursey — APPROVED** [review]
